### ISSUE TITLE
Extend README.md

### ISSUE THREAD

**Issue by gr2m** [pouchdb/pouchdb-auth#1]
The README on pythonhosted.org for the PouchDB Auth plug-in doesn't seem to exist any more:
http://pythonhosted.org/Python-PouchDB/js-plugins.html#pouchdb-auth-plug-in

Do you still have it somewhere? I'm happy to send a pull request and set things into the right format

@marten-de-vries

**Comment by marten-de-vries** [comment]
Thanks for looking into this!

Python-PouchDB is the only project I left on Launchpad considering it actually uses a lot of the advantages it offers (translations, Ubuntu PPAs). The docs are currently still part of Python-PouchDB, so you need to check the source file for that rendering in its git repository. For the JS plugins, that's [here](https://git.launchpad.net/python-pouchdb/tree/docs/js-plugins.rst?id=d5a4a276dca41b36231dc3a569213931125ff4e5).

**Comment by gr2m** [comment]
Thanks, I'm looking into it now

**Comment by gr2m** [comment]
Here is my first (and ongoing) attempt for an extended README:
https://github.com/gr2m/pouchdb-auth/blob/1-readme/README.md
