### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by samhcorney** [pouchdb/pouchdb-auth#10]
Hey,

Great plugin btw!

Is it possible to change passwords once set?

Sam

**Comment by marten-de-vries** [comment]
Yes, it works exactly the same as for CouchDB, you just update the document. IIRC something like this should work (semi-pseudocode)

``` js
// assuming db is a database you can also call login() etc. on
db.get('org.couchdb.user:username').then(function (resp) {// or whatever the exact id is
  resp.password = 'new-password';
  return db.put(resp);
});
```

If you look at the source, you'll see that the sign up function is actually just a tiny wrapper that also just inserts a document.

**Comment by samhcorney** [comment]
@marten-de-vries perfect thanks for the help!
